### PR TITLE
UI tests

### PR DESCRIPTION
**Pull request by carson-katri**

### CODE REVIEW

**Comment by carson-katri** [comment]
Due to some inconsistent bugs, the tests would randomly fail. I enabled an option to run tests up to 3 times to see if they consistently fail. Once we stabilize a bit more, this can be removed.

**Comment by bcardarella** [comment]
@carson-katri is this branch rebase-able?

**Comment by carson-katri** [comment]
This PR is going to be broken now with all of the changes to stylesheets and layouts.

**Comment by bcardarella** [comment]
@carson-katri should we close this or do you want to salvage it at some point?

**Pull request closed without merging**
