### PR TITLE
Include original source in the annotation

### PR DESCRIPTION
**Pull request by NduatiK**
Resolves https://github.com/liveview-native/live_view_native_stylesheet/issues/31

### CODE REVIEW

**Review by bcardarella — APPROVED** [review]

**Review by carson-katri — COMMENTED** [review]
LGTM, but can we hold off on merging until the client-side parsing is updated? I'll open a PR against this branch.

**Comment by carson-katri** [comment]
Will `source` always be a single line?

**Comment by carson-katri** [comment]
@bcardarella @NduatiK Do you have a preferred way for this to be displayed on the client? Here are a few options, but with the metadata it can be formatted in any way:
```
Stylesheet parsing failed for modifier `bold` in class `font-bold`:

/Users/carson.katri/Documents/LiveViewNative/ElixirConf23Apps/elixirconf_chess/lib/elixirconf_chess_web/styles/app_styles.ex:66
   | defmodule ElixirconfChessWeb.Styles.AppStyles do
   | ...
66 | bold()
   | ^ No matching clause found for modifier 'bold'. Expected `bold(_:)`
```

```
Stylesheet parsing failed for modifier `bold` in class `font-bold`:

ElixirconfChessWeb.Styles.AppStyles (/Users/carson.katri/Documents/LiveViewNative/ElixirConf23Apps/elixirconf_chess/lib/elixirconf_chess_web/styles/app_styles.ex:66)
   |
66 | bold()
   | ^ No matching clause found for modifier 'bold'. Expected `bold(_:)`
```

```
Stylesheet parsing failed for modifier `bold` in class `font-bold`:

   |
66 | bold()
   | ^ No matching clause found for modifier 'bold'. Expected `bold(_:)`

in ElixirconfChessWeb.Styles.AppStyles (/Users/carson.katri/Documents/LiveViewNative/ElixirConf23Apps/elixirconf_chess/lib/elixirconf_chess_web/styles/app_styles.ex:66)
```

**Comment by bcardarella** [comment]
@carson-katri #3 looks good to me

**Comment by carson-katri** [comment]
PR open here: https://github.com/NduatiK/liveview-client-swiftui/pull/1

**Comment by NduatiK** [comment]
> Will `source` always be a single line?

Yes

**Pull request merged**
