### PR TITLE
Use core to parse json fragments

### PR DESCRIPTION
**Pull request by simlay**
Depends on https://github.com/liveview-native/liveview-native-core-swift/pull/8
Subtask of https://github.com/liveview-native/liveview-native-core/issues/40
Depends on https://github.com/liveview-native/liveview-native-core/pull/45

### CODE REVIEW

**Comment by bcardarella** [comment]
@simlay I'd like to target this for the v0.3 release after mid January

**Comment by bcardarella** [comment]
@carson-katri @simlay should this be resolved for merging?

**Comment by simlay** [comment]
> @carson-katri @simlay should this be resolved for merging?

We might be able to close this in favor of the work required for #1210.

**Comment by simlay** [comment]
Closed in favor of work required for #1210.

**Pull request closed without merging**
