### PR TITLE
Safely unwrap `NavigationLink` and `Link` URLs

### LINKED ISSUE #1256: NavigationLink view fatal error when no url provided
```heex
<NavigationLink>
  ...
</NavigationLink>
```

results in this:

Screenshot 2024-02-02 at 10 52 45 AM

In the event of a missing `url` attribute it should just render and not error like this.

### PR DESCRIPTION
**Pull request by carson-katri**
Closes #1256 

If the URL is invalid, the content of the View will be rendered instead.

### CODE REVIEW

**Comment by bcardarella** [comment]
I agree with the unwrapping in the event of missing arguments. I'm wondering though if we should also log a warning?

**Comment by carson-katri** [comment]
This will now log when missing the `destination` attribute:
```
Missing or invalid `destination` on `<Link>Test</Link>`
Missing or invalid `destination` on `<NavigationLink>Test</NavigationLink>`
```

**Comment by bcardarella** [comment]
@carson-katri if I'm understanding correctly the unwrap will just render the content and hoist? Does that mean if any modifiers are applied to `Link` and `NavigationLink` that are meant to apply to child views will be lost? If that's the case can we just replace with `Group` as the container, copy the modifiers over, and not hoist?

**Comment by carson-katri** [comment]
Modifiers are still applied.

**Review by bcardarella — APPROVED** [review]

**Pull request merged**
