### PR TITLE
Add ExDoc documentation generation for SwiftUI Views

### PR DESCRIPTION
**Pull request by carson-katri**
This will use the JSON produced by Apple's DocC to generate markdown files for ExDoc.

To try it out:

1. Generate the Swift documentation extensions

```sh
xcrun swift package plugin --allow-writing-to-package-directory generate-documentation-extensions
```

2. Build documentation with DocC

```sh
xcodebuild docbuild -scheme LiveViewNative -destination generic/platform=iOS -derivedDataPath docc_build -skipMacroValidation -skipPackagePluginValidation
```

3. Generate ExDoc `extras`

```sh
mix lvn.swift_ui.generate_documentation
```

4. Build documentation with ExDoc

```sh
mix docs
```

Screenshot 2024-02-15 at 2 00 48 PM (1)

### CODE REVIEW

**Comment by carson-katri** [comment]
We can generate cheatsheets too, which could be useful for a quick look at the code samples in the documentation:

Screenshot 2024-02-15 at 4 35 26 PM

**Comment by bcardarella** [comment]
yes, please

**Comment by carson-katri** [comment]
Tooltips are now supported for links to views, attributes, and events.

https://github.com/liveview-native/liveview-client-swiftui/assets/13581484/a5ab3b19-54ea-47ce-bd11-afbac2890551

**Comment by AZholtkevych** [comment]
@BrooklinJazz could you please review that one

**Comment by BrooklinJazz** [comment]
@carson-katri I seem to be getting an error when I try to run the first command:

```
liveview-client-swiftui % xcrun swift package plugin --allow-writing-to-package-directory generate-documentation-extensions

warning: could not determine XCTest paths: terminated(1): /usr/bin/xcrun --sdk macosx --show-sdk-platform-path output:
    xcrun: error: unable to lookup item 'PlatformPath' from command line tools installation
    xcrun: error: unable to lookup item 'PlatformPath' in SDK '/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk'
    
error: 'liveview-client-swiftui': Invalid manifest (compiled with: ["/Library/Developer/CommandLineTools/usr/bin/swiftc", "-vfsoverlay", "/var/folders/67/286j4b4x6gsgz5qh8qsry66c0000gp/T/TemporaryDirectory.Xeh1Q8/vfs.yaml", "-L", "/Library/Developer/CommandLineTools/usr/lib/swift/pm/ManifestAPI", "-lPackageDescription", "-Xlinker", "-rpath", "-Xlinker", "/Library/Developer/CommandLineTools/usr/lib/swift/pm/ManifestAPI", "-target", "arm64-apple-macosx13.0", "-sdk", "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk", "-swift-version", "5", "-I", "/Library/Developer/CommandLineTools/usr/lib/swift/pm/ManifestAPI", "-sdk", "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk", "-package-description-version", "5.9.0", "/Users/brooklin/liveview-client-swiftui/Package.swift", "-Xfrontend", "-disable-implicit-concurrency-module-import", "-Xfrontend", "-disable-implicit-string-processing-module-import", "-o", "/var/folders/67/286j4b4x6gsgz5qh8qsry66c0000gp/T/TemporaryDirectory.jpjlkd/liveview-client-swiftui-manifest"])
/Users/brooklin/liveview-client-swiftui/Package.swift:5:8: error: no such module 'CompilerPluginSupport'
import CompilerPluginSupport
```

Any thoughts on how I can resolve the issue so I can continue the review?

**Comment by BrooklinJazz** [comment]
Seems like the docc_build folder is causing an issue with ElixirLS (I also tried elixir-tools). I'm looking into configuration options to ignore the folder and resolve the issue.

**Comment by BrooklinJazz** [comment]
> @carson-katri I seem to be getting an error when I try to run the first command:
> 
> ```
> liveview-client-swiftui % xcrun swift package plugin --allow-writing-to-package-directory generate-documentation-extensions
> 
> warning: could not determine XCTest paths: terminated(1): /usr/bin/xcrun --sdk macosx --show-sdk-platform-path output:
>     xcrun: error: unable to lookup item 'PlatformPath' from command line tools installation
>     xcrun: error: unable to lookup item 'PlatformPath' in SDK '/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk'
>     
> error: 'liveview-client-swiftui': Invalid manifest (compiled with: ["/Library/Developer/CommandLineTools/usr/bin/swiftc", "-vfsoverlay", "/var/folders/67/286j4b4x6gsgz5qh8qsry66c0000gp/T/TemporaryDirectory.Xeh1Q8/vfs.yaml", "-L", "/Library/Developer/CommandLineTools/usr/lib/swift/pm/ManifestAPI", "-lPackageDescription", "-Xlinker", "-rpath", "-Xlinker", "/Library/Developer/CommandLineTools/usr/lib/swift/pm/ManifestAPI", "-target", "arm64-apple-macosx13.0", "-sdk", "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk", "-swift-version", "5", "-I", "/Library/Developer/CommandLineTools/usr/lib/swift/pm/ManifestAPI", "-sdk", "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk", "-package-description-version", "5.9.0", "/Users/brooklin/liveview-client-swiftui/Package.swift", "-Xfrontend", "-disable-implicit-concurrency-module-import", "-Xfrontend", "-disable-implicit-string-processing-module-import", "-o", "/var/folders/67/286j4b4x6gsgz5qh8qsry66c0000gp/T/TemporaryDirectory.jpjlkd/liveview-client-swiftui-manifest"])
> /Users/brooklin/liveview-client-swiftui/Package.swift:5:8: error: no such module 'CompilerPluginSupport'
> import CompilerPluginSupport
> ```
> 
> Any thoughts on how I can resolve the issue so I can continue the review?

Also, we resolved this issue with the following command: `sudo xcode-select --switch /Applications/Xcode.app`

**Review by BrooklinJazz — CHANGES_REQUESTED** [review]
I made a PR with some suggested additions: https://github.com/liveview-native/liveview-client-swiftui/pull/1276

Feel free to merge it in, or adapt the changes however you see fit!

**Comment by bcardarella** [comment]
Is this good for review? I see the one changes requested still

**Comment by carson-katri** [comment]
It's ready for another review. I merged in Brooklin's changes, and then made some minor tweaks.

**Pull request merged**
