### PR TITLE
Support multi-item selection

### LINKED ISSUE #1213: Support multiple List row selections
Currently, you can only select one item at a time with a list. This should be changed to allow multiple elements as well. One way to do this would be allowing a JSON encoded array of string IDs to be passed to `selection`.

### PR DESCRIPTION
**Pull request by carson-katri**
Closes #1213 

Pass a JSON encoded array to allow for multi-select. This also works with the `EditButton` element.

```ex
def mount(_params, _session, socket) do
  {:ok, assign(socket, selection: [])}
end

def render(%{format: :swiftui} = assigns) do
  ~SWIFTUI"""
  <EditButton />
  <List selection={Jason.encode!(@selection)} phx-change="selection-changed">
    <Text id={"#{i}"} :for={i <- 1..10}><%= i %></Text>
  </List>
  """
end

def handle_event("selection-changed", %{ "selection" => selection }, socket) do
  {:noreply, assign(socket, selection: selection)}
end
```

https://github.com/liveview-native/liveview-client-swiftui/assets/13581484/c9ac86fc-a8d9-43c3-bb2f-af951620482e

### CODE REVIEW

**Comment by carson-katri** [comment]
@bcardarella Is it possible to have the LVN engine automatically JSON encode list attributes?

Do you have an example of the Phoenix select options I could look at?

**Comment by bcardarella** [comment]
We could but let me first find out if there are any traps with doing this

**Comment by BrooklinJazz** [comment]
> @bcardarella Is it possible to have the LVN engine automatically JSON encode list attributes?
> 
> Do you have an example of the Phoenix select options I could look at?

@carson-katri in the `.input` core component, this function converts a keyword list and a select value into the options for a select element.
https://hexdocs.pm/phoenix_html/3.3.3/Phoenix.HTML.Form.html#options_for_select/2

This is how it's defined in core components:

```elixir
  def input(%{type: "select"} = assigns) do
    ~H"""
    <div phx-feedback-for={@name}>
      <.label for={@id}><%= @label %></.label>
      <select
        id={@id}
        name={@name}
        class="mt-2 block w-full rounded-md border border-gray-300 bg-white shadow-sm focus:border-zinc-400 focus:ring-0 sm:text-sm"
        multiple={@multiple}
        {@rest}
      >
        <option :if={@prompt} value=""><%= @prompt %></option>
        <%= Phoenix.HTML.Form.options_for_select(@options, @value) %>
      </select>
      <.error :for={msg <- @errors}><%= msg %></.error>
    </div>
    """
  end
```

Meaning options can be defined like so:

```elixir
<.input type="select" options={["label": "value", "label2": "value2"]}/>
```

Hope that gives some inspiration!

**Comment by AZholtkevych** [comment]
@carson-katri could you please merge it if it is finished? Thank you so much

**Pull request merged**
